# Generated by Django 5.0.7 on 2024-08-01 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_reinitial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
