# Generated by Django 5.0.7 on 2024-08-01 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='expirationDate',
            field=models.DateField(editable=False),
        ),
    ]
