# Generated by Django 5.0.6 on 2024-07-11 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_orderproduct_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='Additional_Message',
            new_name='additionalMessage',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='ProductName',
            new_name='productName',
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
