# Generated by Django 5.0.7 on 2024-07-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_additional_message_order_additionalmessage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='expirationDate',
            field=models.DateTimeField(editable=False),
        ),
    ]
