# Generated by Django 5.0.7 on 2024-07-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_order_expirationdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='additionalMessage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
