# Generated by Django 5.0.7 on 2026-05-02 22:37

from django.db import migrations


def seed_locations(apps, schema_editor):
    Location = apps.get_model("api", "Location")

    locations = [
        "Parkland",
        "Lakewood",
        "Downtown Tacoma",
        "Olympia",
        "Tumwater",
        "University Place",
        "Shelton",
        "Bremerton",
        "Chehalis",
    ]

    id = 1

    for name in locations:
        Location.objects.get_or_create(id = id, location=name)
        id += 1

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_location"),
    ]

    operations = [
        migrations.RunPython(seed_locations),
    ]
