# Generated by Django 5.0.7 on 2026-05-02 22:37

from django.db import migrations


def seed_locations(apps, schema_editor):
    Location = apps.get_model("api", "Location")

    locations = [
        "Parkland",
        "Lakewood",
        "Downtown Tacoma",
        "Olympia",
        "Tumwater",
        "University Place",
        "Shelton",
        "Bremerton",
        "Chehalis",
    ]

    for name in locations:
        Location.objects.get_or_create(location=name)

def unseed_locations(apps, schema_editor):
    Location = apps.get_model("api", "Location")

    locations = [
        "Parkland",
        "Lakewood",
        "Downtown Tacoma",
        "Olympia",
        "Tumwater",
        "University Place",
        "Shelton",
        "Bremerton",
        "Chehalis",
    ]

    Location.objects.filter(location__in=locations).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_location"),
    ]

    operations = [
        migrations.RunPython(seed_locations, unseed_locations)
    ]
